### ISSUE TITLE
cordova create step is missing.

### ISSUE THREAD

**Issue by m9dfukc** [zentrope/phone-scratch#1]
Hey,

running "cordova add platform ios" in the client folder results in "Current working directory is not a Cordova-based project.". Seems the "cordova create ..." step is missing – or I get something wrong?! 

fyi, I'm using Cordova 5.0.0

**Comment by zentrope** [comment]
Hm. I've not even looked at this stuff for months.

Are you using the "master" branch as an example, or the port I was working with on the "leinify" branch?

Also, this might interest you:

https://github.com/nodename/cordova-om-template

**Comment by zentrope** [comment]
Oh, I'll upgrade Cordova and review the docs by tonight (PST) and update accordingly.

**Comment by m9dfukc** [comment]
I tried booth branches. I ended up with the "leinify" branch and got it kinda working. I had to change a few things and the readme lacks quite a few steps.

Looking forward to your updates. Thanks

**Comment by zentrope** [comment]
The `master` branch was where I ended up before deciding I knew enough to try something different. The `leinify` branch wasn't complete at all and the docs not even touched.

I'm so glad you could get something useful out of any of it anyway!

I don't actually use Cordova, but might in the future if certain circumstances play out as much as I hope. ;)

**Comment by zentrope** [comment]
Okay, the main "master" stuff works. Removed sente because it was conflicting with the latest CLJS for some reason. Updated boot stuff, readme docs, use of non-global npm dependencies, etc, etc.

BTW, the original problem you noted was really a documentation prob.

> boot cordova

would have solved it. I think.
